categorias = {
    # ============ IMÁGENES ============
    ".jpg": "Imágenes",
    ".jpeg": "Imágenes",
    ".png": "Imágenes",
    ".gif": "Imágenes",
    ".bmp": "Imágenes",
    ".tiff": "Imágenes",
    ".tif": "Imágenes",
    ".webp": "Imágenes",
    ".svg": "Imágenes",
    ".ico": "Imágenes",
    ".heic": "Imágenes",
    ".heif": "Imágenes",
    ".raw": "Imágenes",
    ".cr2": "Imágenes",
    ".nef": "Imágenes",
    ".arw": "Imágenes",
    ".dng": "Imágenes",

    # ============ DISEÑO GRÁFICO ============
    ".psd": "Diseño",
    ".ai": "Diseño",
    ".eps": "Diseño",
    ".indd": "Diseño",
    ".xcf": "Diseño",
    ".sketch": "Diseño",
    ".fig": "Diseño",
    ".cdr": "Diseño",
    ".afphoto": "Diseño",
    ".afdesign": "Diseño",
    ".afpub": "Diseño",

    # ============ MODELOS 3D Y CAD ============
    ".blend": "3D",
    ".fbx": "3D",
    ".obj": "3D",
    ".stl": "3D",
    ".dae": "3D",
    ".glb": "3D",
    ".gltf": "3D",
    ".3ds": "3D",
    ".max": "3D",
    ".ma": "3D",
    ".mb": "3D",
    ".c4d": "3D",
    ".dxf": "CAD",
    ".dwg": "CAD",
    ".skp": "CAD",
    ".step": "CAD",
    ".stp": "CAD",
    ".iges": "CAD",
    ".igs": "CAD",
    ".sldprt": "CAD",
    ".sldasm": "CAD",

    # ============ DOCUMENTOS DE TEXTO ============
    ".pdf": "Documentos",
    ".doc": "Documentos",
    ".docx": "Documentos",
    ".odt": "Documentos",
    ".rtf": "Documentos",
    ".txt": "Documentos",
    ".md": "Documentos",
    ".markdown": "Documentos",
    ".tex": "Documentos",
    ".wpd": "Documentos",
    ".pages": "Documentos",

    # ============ HOJAS DE CÁLCULO ============
    ".xls": "Hojas de cálculo",
    ".xlsx": "Hojas de cálculo",
    ".xlsm": "Hojas de cálculo",
    ".xlsb": "Hojas de cálculo",
    ".ods": "Hojas de cálculo",
    ".csv": "Hojas de cálculo",
    ".tsv": "Hojas de cálculo",
    ".numbers": "Hojas de cálculo",
    ".gsheet": "Hojas de cálculo",

    # ============ PRESENTACIONES ============
    ".ppt": "Presentaciones",
    ".pptx": "Presentaciones",
    ".pptm": "Presentaciones",
    ".pps": "Presentaciones",
    ".ppsx": "Presentaciones",
    ".odp": "Presentaciones",
    ".key": "Presentaciones",
    ".gslides": "Presentaciones",

    # ============ MÚSICA / AUDIO ============
    ".mp3": "Música",
    ".wav": "Música",
    ".flac": "Música",
    ".aac": "Música",
    ".ogg": "Música",
    ".m4a": "Música",
    ".wma": "Música",
    ".opus": "Música",
    ".mid": "Música",
    ".midi": "Música",
    ".aiff": "Música",
    ".alac": "Música",
    ".ape": "Música",
    ".ac3": "Música",
    ".dts": "Música",
    ".amr": "Música",

    # ============ VIDEOS ============
    ".mp4": "Videos",
    ".mkv": "Videos",
    ".avi": "Videos",
    ".mov": "Videos",
    ".wmv": "Videos",
    ".flv": "Videos",
    ".webm": "Videos",
    ".m4v": "Videos",
    ".mpg": "Videos",
    ".mpeg": "Videos",
    ".3gp": "Videos",
    ".ogv": "Videos",
    ".vob": "Videos",
    ".rm": "Videos",
    ".ts": "Videos",
    ".mts": "Videos",
    ".m2ts": "Videos",
    # ============ SUBTÍTULOS (dentro de Videos) ============
    ".srt": "Videos",
    ".sub": "Videos",
    ".vtt": "Videos",
    ".ass": "Videos",
    ".ssa": "Videos",
    ".sbv": "Videos",
    ".dfxp": "Videos",
    ".ttml": "Videos",
    ".mpl": "Videos",
    ".usf": "Videos",
    ".stl": "Videos",
    ".cap": "Videos",
    ".scc": "Videos",
    ".smi": "Videos",
    ".rt": "Videos",
    ".idx": "Videos",    # Acompaña a .sub (VobSub)

    # ============ ARCHIVOS COMPRIMIDOS ============
    ".zip": "Comprimidos",
    ".rar": "Comprimidos",
    ".7z": "Comprimidos",
    ".tar": "Comprimidos",
    ".gz": "Comprimidos",
    ".bz2": "Comprimidos",
    ".xz": "Comprimidos",
    ".tgz": "Comprimidos",
    ".tbz2": "Comprimidos",
    ".lz": "Comprimidos",
    ".z": "Comprimidos",
    ".cab": "Comprimidos",
    ".ace": "Comprimidos",
    ".arc": "Comprimidos",

    # ============ IMÁGENES DE DISCO ============
    ".iso": "Imágenes de disco",
    ".dmg": "Imágenes de disco",
    ".vhd": "Imágenes de disco",
    ".vmdk": "Imágenes de disco",
    ".img": "Imágenes de disco",

    # ============ EJECUTABLES Y PAQUETES ============
    ".exe": "Ejecutables",
    ".msi": "Ejecutables",
    ".apk": "Ejecutables móviles",
    ".app": "Ejecutables macOS",
    ".deb": "Paquetes",
    ".rpm": "Paquetes",
    ".run": "Ejecutables Linux",
    ".bin": "Binarios",
    ".jar": "Java",
    ".bat": "Scripts",
    ".cmd": "Scripts",
    ".sh": "Scripts",
    ".ps1": "Scripts",

    # ============ CÓDIGO FUENTE ============
    ".py": "Código fuente",
    ".js": "Código fuente",
    ".ts": "Código fuente",
    ".java": "Código fuente",
    ".c": "Código fuente",
    ".cpp": "Código fuente",
    ".h": "Código fuente",
    ".hpp": "Código fuente",
    ".cs": "Código fuente",
    ".php": "Código fuente",
    ".rb": "Código fuente",
    ".go": "Código fuente",
    ".rs": "Código fuente",
    ".swift": "Código fuente",
    ".kt": "Código fuente",
    ".scala": "Código fuente",
    ".pl": "Código fuente",
    ".lua": "Código fuente",
    ".r": "Código fuente",
    ".m": "Código fuente",
    ".vb": "Código fuente",
    ".fs": "Código fuente",

    # ============ WEB ============
    ".html": "Web",
    ".htm": "Web",
    ".css": "Web",
    ".asp": "Web",
    ".aspx": "Web",
    ".jsp": "Web",
    ".wasm": "Web",

    # ============ DATOS Y CONFIGURACIÓN ============
    ".xml": "Datos",
    ".json": "Datos",
    ".yml": "Datos",
    ".yaml": "Datos",
    ".ini": "Configuración",
    ".cfg": "Configuración",
    ".conf": "Configuración",
    ".env": "Configuración",
    ".toml": "Configuración",
    ".properties": "Configuración",
    ".lock": "Dependencias",
    ".gitignore": "Configuración",

    # ============ BASES DE DATOS ============
    ".db": "Bases de datos",
    ".sqlite": "Bases de datos",
    ".sqlite3": "Bases de datos",
    ".sql": "Bases de datos",
    ".mdb": "Bases de datos",
    ".accdb": "Bases de datos",
    ".dbf": "Bases de datos",
    ".pdb": "Bases de datos",
    ".frm": "Bases de datos",
    ".myd": "Bases de datos",
    ".myi": "Bases de datos",

    # ============ FUENTES TIPOGRÁFICAS ============
    ".ttf": "Fuentes",
    ".otf": "Fuentes",
    ".woff": "Fuentes",
    ".woff2": "Fuentes",
    ".eot": "Fuentes",

    # ============ LIBROS / EBOOKS ============
    ".epub": "Libros",
    ".mobi": "Libros",
    ".azw": "Libros",
    ".azw3": "Libros",
    ".fb2": "Libros",
    ".djvu": "Libros",
    ".chm": "Libros",

    # ============ CORREOS Y CONTACTOS ============
    ".eml": "Correos",
    ".msg": "Correos",
    ".pst": "Correos",
    ".ost": "Correos",
    ".mbox": "Correos",
    ".vcf": "Contactos",
    ".ics": "Calendario",

    # ============ SEGURIDAD Y CERTIFICADOS ============
    ".cer": "Certificados",
    ".crt": "Certificados",
    ".pem": "Certificados",
    ".pub": "Claves públicas",
    ".gpg": "Cifrado",
    ".asc": "Cifrado",
    ".kdbx": "Contraseñas",
    ".ovpn": "VPN",

    # ============ ACCESOS DIRECTOS ============
    ".url": "Accesos directos",
    ".lnk": "Accesos directos",
    ".desktop": "Accesos directos",
    ".webloc": "Accesos directos",

    # ============ SISTEMA Y TEMPORALES ============
    ".dll": "Sistema",
    ".so": "Sistema",
    ".dylib": "Sistema",
    ".sys": "Sistema",
    ".drv": "Sistema",
    ".reg": "Registro",
    ".inf": "Controladores",
    ".cat": "Catálogos",
    ".msc": "Consolas",
    ".cpl": "Panel de control",
    ".scr": "Protectores de pantalla",
    ".theme": "Temas",
    ".themepack": "Temas",
    ".tmp": "Temporales",
    ".bak": "Copias de seguridad",
    ".old": "Copias de seguridad",
    ".sav": "Partidas guardadas",
    ".log": "Registros",
    ".torrent": "Torrents",
}